services:
  postgres:
    image: postgres:16-alpine
    container_name: smartpay-postgres
    environment:
      POSTGRES_DB: smartpay_db
      POSTGRES_USER: smartpay_admin
      POSTGRES_PASSWORD: smartpay_secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartpay_admin -d smartpay_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
    container_name: smartpay-redpanda
    command:
      - redpanda start
      - --kafka-addr internal://0.0.0.0:29092,external://0.0.0.0:9092
      - --advertise-kafka-addr internal://redpanda:29092,external://localhost:9092
      - --pandaproxy-addr internal://0.0.0.0:28082
      - --advertise-pandaproxy-addr internal://redpanda:28082
      - --schema-registry-addr internal://0.0.0.0:28081
      - --smp 1
      - --memory 512M
      - --mode dev-container
      - --default-log-level=info
    ports:
      - "9092:9092"
    volumes:
      - redpandadata:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true'"]
      interval: 5s
      timeout: 5s
      retries: 5

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.7.2
    container_name: smartpay-redpanda-console
    ports:
      - "8090:8080"
    environment:
      KAFKA_BROKERS: redpanda:29092
    depends_on:
      redpanda:
        condition: service_healthy

volumes:
  pgdata:
  redpandadata:
