apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smartpay-gateway-hpa
  namespace: smartpay
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smartpay-gateway
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smartpay-payment-service-hpa
  namespace: smartpay
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smartpay-payment-service
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smartpay-ledger-service-hpa
  namespace: smartpay
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smartpay-ledger-service
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smartpay-invoice-service-hpa
  namespace: smartpay
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smartpay-invoice-service
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smartpay-notification-service-hpa
  namespace: smartpay
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smartpay-notification-service
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
