apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartpay-payout-worker
  namespace: smartpay
  labels:
    app.kubernetes.io/name: smartpay-payout-worker
    app.kubernetes.io/component: factoring-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: smartpay-payout-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smartpay-payout-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: worker
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          image: ghcr.io/hozgan/smartpay/smartpay-payout-worker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8084
          envFrom:
            - configMapRef:
                name: smartpay-common-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            periodSeconds: 5
