#!/usr/bin/env bash
# ==============================================================================
# Sync per-service Flyway migration ConfigMaps for Kubernetes
# ==============================================================================
# Each service's Flyway migrations live in its own module:
#   <module>/src/main/resources/db/migration/*.sql
# This script generates one ConfigMap per DB-backed service (single source of
# truth = module resources). The per-service migration Jobs in k8s/migrations/
# mount these ConfigMaps and apply them to the service's own PostgreSQL schema.
#
# Usage:  scripts/ci/sync-flyway-configmaps.sh
# Output: k8s/migrations/configmaps/smartpay-<svc>-flyway-scripts.yaml
# ==============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_DIR="${REPO_ROOT}/k8s/migrations/configmaps"
mkdir -p "${OUT_DIR}"

# schema|module  (schema must match spring.flyway.schemas / default-schema in the service)
SERVICES=(
  "ledger|smartpay-ledger-service"
  "invoice|smartpay-invoice-service"
  "payment|smartpay-payment-service"
  "recon|smartpay-recon-service"
  "gateway|smartpay-gateway"
  "risk|smartpay-risk-service"
  "notification|smartpay-notification-service"
)

for entry in "${SERVICES[@]}"; do
  schema="${entry%%|*}"
  module="${entry##*|}"
  migration_dir="${REPO_ROOT}/${module}/src/main/resources/db/migration"
  configmap_name="smartpay-${schema}-flyway-scripts"
  out_file="${OUT_DIR}/${configmap_name}.yaml"

  if [[ ! -d "${migration_dir}" ]]; then
    echo "SKIP ${schema}: no migration dir at ${migration_dir}" >&2
    continue
  fi
  if ! compgen -G "${migration_dir}/V*.sql" >/dev/null; then
    echo "SKIP ${schema}: no V*.sql migrations in ${migration_dir}" >&2
    continue
  fi

  # Build the ConfigMap manifest without requiring a live cluster.
  {
    echo "# Auto-generated by scripts/ci/sync-flyway-configmaps.sh — DO NOT EDIT."
    echo "# Source: ${module}/src/main/resources/db/migration"
    echo "apiVersion: v1"
    echo "kind: ConfigMap"
    echo "metadata:"
    echo "  name: ${configmap_name}"
    echo "  namespace: smartpay"
    echo "  labels:"
    echo "    app.kubernetes.io/part-of: smartpay-platform"
    echo "    app.kubernetes.io/component: db-migration"
    echo "    app.kubernetes.io/instance: ${schema}"
    echo "data:"
    for sql in "${migration_dir}"/V*.sql; do
      fname="$(basename "${sql}")"
      echo "  ${fname}: |-"
      sed 's/^/    /' "${sql}"
    done
  } > "${out_file}"

  echo "WROTE ${out_file}"
done
