apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartpay-ledger-service
  namespace: smartpay
  labels:
    app.kubernetes.io/name: smartpay-ledger-service
    app.kubernetes.io/component: ledger-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: smartpay-ledger-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smartpay-ledger-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ledger
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          image: ghcr.io/hozgan/smartpay/smartpay-ledger-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
            - name: grpc
              containerPort: 9090
          envFrom:
            - configMapRef:
                name: smartpay-common-config
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres.smartpay.svc.cluster.local:5432/smartpay_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smartpay-db-app-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartpay-db-app-credentials
                  key: password
            - name: GRPC_PORT
              value: "9090"
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 1000m
              memory: 768Mi
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 36
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: smartpay-ledger-service
  namespace: smartpay
  labels:
    app.kubernetes.io/name: smartpay-ledger-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: smartpay-ledger-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: grpc
      port: 9090
      targetPort: 9090
