apiVersion: v1
kind: ConfigMap
metadata:
  name: smartpay-common-config
  namespace: smartpay
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  REDPANDA_BOOTSTRAP_SERVERS: "redpanda.smartpay.svc.cluster.local:9092"
  LEDGER_GRPC_HOST: "smartpay-ledger-service.smartpay.svc.cluster.local"
  LEDGER_GRPC_PORT: "9090"
