apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - common-configmap.yaml
  - network-policy.yaml
  - services/smartpay-gateway/deployment.yaml
  - services/smartpay-ledger-service/deployment.yaml
  - services/smartpay-payment-service/deployment.yaml
  - services/smartpay-invoice-service/deployment.yaml
  - services/smartpay-payout-worker/deployment.yaml
  - services/smartpay-recon-service/deployment.yaml
  - services/smartpay-risk-service/deployment.yaml
  - services/smartpay-notification-service/deployment.yaml
