apiVersion: v1
kind: Namespace
metadata:
  name: smartpay
  labels:
    app.kubernetes.io/part-of: smartpay-platform
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
