apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smartpay

resources:
  - ../../base

labels:
  - pairs:
      environment: staging

# In staging, maintain 2 replicas for multi-pod HA verification
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: smartpay-gateway
      spec:
        replicas: 2
    target:
      kind: Deployment
      name: smartpay-gateway
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: smartpay-ledger-service
      spec:
        replicas: 2
    target:
      kind: Deployment
      name: smartpay-ledger-service
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: smartpay-payment-service
      spec:
        replicas: 2
    target:
      kind: Deployment
      name: smartpay-payment-service
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: smartpay-invoice-service
      spec:
        replicas: 2
    target:
      kind: Deployment
      name: smartpay-invoice-service
